#!/usr/bin/env php
<?php
require __DIR__."/vendor/autoload.php";
use Symfony\Component\Console\Application;
use Kononov\SumCommand;

$app = new Application('Welcome', "v1.0.0");
$app = add(new SummCommand());
$app -> run();
